### ISSUE TITLE
Video embeded in iframe in readme is not displayed

### ISSUE THREAD

**Issue by jibe-b** [loomio/loomio-coop-handbook#16]
The html iframe element in the readme is not interpreted by github, resulting in this:

![image](https://user-images.githubusercontent.com/6146483/50334910-039ddd00-050a-11e9-99bc-bb6e8aba5a56.png)

**Comment by rdbartlett** [comment]
This is behaving as expected. Github hosts the files, which are correctly rendered on http://loomio.coop/

**Comment by jibe-b** [comment]
Ok.
