### ISSUE TITLE
www subdomain

### ISSUE THREAD

**Issue by benjaoming** [loomio/loomio-coop-handbook#9]
`www.loomio.coop` is broken, but works without prepending `www.`

Supposing this is an issue since I can see from my browsing history that I used to visit `www.loomio.coop`

Thanks!
Ben

**Comment by rdbartlett** [comment]
thanks for the report! 

@robguthrie can you haz remedy?

**Comment by robguthrie** [comment]
Update. I've been trying to fix this over the course of the day. I think I might be stupid but I'll have it sorted by tomorrow. Thanks for the bug report!

**Comment by robguthrie** [comment]
Ok this is fixed!
